server:
  port: 3030

spring:
  application:
    name: chat-service

  redis:
    host: localhost
    port: 6379


eureka:
  instance:
    instance-id: chat-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server_image : "{cipher}524f0f565420ca6bd554c8d9183c98fb41bb7727ab911f91fe9dcf1edbfb422d5835f3cc4a860c321e5d4ba9c9e0ecd7b650a62f539f9f35cb5416f33d4d401ab8b9141ad66589ebfd8bfb97948740c5835c15ea8acf26f5ab1c10fab6336a2d"

state-management-url : http://localhost:8090/state/